nginx:
  image: bitnami/nginx
  ports:
    - "8888:8888"
  links:
    - phpfpm:yourapp
  volumes:
    - ./vhosts:/bitnami/nginx/conf/vhosts

phpfpm:
  image: bitnami/php-fpm
  volumes:
    - ./app:/app

kong-dash:
  image: pgbi/kong-dashboard
  restart: always
  ports:
    - "8080:8080"

kong:
  image: mashape/kong:latest
  restart: always
  external_links:
    - kong-database:kong-database
    - access_control_nginx:access-control
  ports:
    - "8000:8000"
    - "8443:8443"
    - "8001:8001"
    - "7946:7946"
    - "7946:7946/udp"
  environment:
    - DATABASE=cassandra
